logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: trace

    # for native query
    org.springframework.transaction: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE