server:
  port: 8090
  error:
    include-exception: false      # Response 에 Exception 을 표시할지
    include-message: always       # Response 에 Exception Message 를 표시할지 (never | always | on_param)
    include-stacktrace: on_param  # Response 에 Stack Trace 를 표시할지 (never | always | on_param) on_trace_params 은 deprecated
    whitelabel.enabled: true      # 에러 발생 시 Spring 기본 에러 페이지 노출 여부
    include-binding-errors: always

spring:
  profiles:
    active: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/petsignal?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 6351614
    connection-test-query: SELECT NOW() FROM dual


  #  web 404 throw
  mvc:
    throw-exception-if-no-handler-found: true
    dispatch-options-request: false
  web:
    resources:
      add-mappings: false

  output:
    ansi:
      enabled: always

jwt:
  secret: com.bank.petsignal.jwt.security.key
  issuer: com.bank.petsignal
  audience: petsignal-shop
  # access-expiration: 1480000
  # access-expiration: 60
  # 14 ?
  access-expiration: 600
  # 14 ?
  refresh-expiration: 1480000

logging:
  level:
    org.hibernate.SQL: ERROR
    org.hibernate.type: trace

    # for native query
    org.springframework.jdbc.core.JdbcTemplate: ERROR
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE